version: '3.7'

services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - v_portainer:/data
    restart: always

volumes:
  v_portainer:
